Repository Hyundai-Charowner/Sac-FE, pull requests merged in 2023-12, with the labels that each got.

#2 [Settings] 리액트 프로젝트 기초 셋팅
  sac/.gitignore
  sac/README.md
  sac/package-lock.json
  sac/package.json
  sac/public/favicon.ico
  sac/public/index.html
  sac/public/logo192.png
  sac/public/logo512.png
  sac/public/manifest.json
  sac/public/robots.txt
  sac/src/App.css
  sac/src/App.js
  sac/src/App.test.js
  sac/src/index.css
  sac/src/index.js
  sac/src/logo.svg
  sac/src/reportWebVitals.js
  sac/src/setupTests.js
Labels: ⚙Setting

#15 UI/detail components 생성
  sac/package-lock.json
  sac/package.json
  sac/src/Page/Home.js
  sac/src/assets/image/upload.png
  sac/src/components/Header/Header.js
  sac/src/components/Post/Post.js
  sac/src/components/Post/PostBody.js
  sac/src/components/Post/PostDetail.js
  sac/src/components/Post/PostFooter.js
  sac/src/components/Post/PostHeader.js
  sac/src/components/Post/PostReply.js
  sac/src/components/Post/Reply.js
  sac/src/components/Post/ReplyEdit.js
  sac/src/home/Home.js
  sac/src/index.js
  sac/src/styles/Home.css
  sac/src/styles/Post.css
  sac/src/styles/PostReply.css
  sac/src/styles/RightNavi.css
Labels: 🎨UI

#18 Feature/좋아요 클릭 이벤트 추가
  sac/src/assets/image/heartFalse.png
  sac/src/components/Post/Post.js
  sac/src/components/Post/PostFooter.js
  sac/src/styles/Post.css
Labels: 🐯Feature

#24 [Feature] Login 기능 활성화
  sac/src/Page/Home.js
  sac/src/assets/image/community.png
  sac/src/assets/image/googleIcon.png
  sac/src/assets/image/logoImage.png
  sac/src/assets/image/talk.png
  sac/src/components/Header/Header.js
  sac/src/components/Login/GoogleLogInButton.js
  sac/src/components/Login/Login.js
  sac/src/components/User/UserInfo.js
  sac/src/styles/Header.css
  sac/src/styles/Login.css
  sac/src/styles/Modal.js
  sac/src/styles/UserInfo.css
  sac/src/utils/SendOAuthDataToServer.js
Labels: 🐯Feature

#39 Setting/react router dom 설정
  sac/src/App.js
  sac/src/Page/Home.js
  sac/src/components/Login/Login.js
  sac/src/styles/Login.css
Labels: ⚙Setting

#41 UI/글 쓰기 생성
  sac/package-lock.json
  sac/package.json
  sac/src/App.js
  sac/src/Page/Home.js
  sac/src/Page/Write.js
  sac/src/components/Post/PostButton.js
  sac/src/components/Write/WriteBody.js
  sac/src/index.js
  sac/src/reportWebVitals.js
  sac/src/styles/Button.css
  sac/src/styles/Home.css
  sac/src/styles/Write.css
Labels: 🎨UI

#44 오류수정1
  sac/src/components/Login/Login.js
Labels: 🐞Bug/fix

#46 [Feature]문의하기 로직 추가
  sac/src/components/Navi/RightNavi/RightNavi.js
  sac/src/styles/RightNavi.css
Labels: 🐯Feature

#50 [UI]mypage 생성
  sac/src/App.js
  sac/src/Page/MyPage.js
  sac/src/assets/image/userDefault.png
  sac/src/components/MyPage/MyBody.js
  sac/src/components/MyPage/MyLikePost.js
  sac/src/components/MyPage/MyNavi.js
  sac/src/components/MyPage/MyPost.js
  sac/src/components/MyPage/MyReply.js
  sac/src/components/Navi/LeftNavi/LeftNavi.js
  sac/src/components/Post/PostReply.js
  sac/src/components/User/UserInfo.js
  sac/src/components/commons/Reply.js
  sac/src/components/commons/TopicItem.js
  sac/src/styles/Header.css
  sac/src/styles/MyPage.css
  sac/src/styles/MyPageBody.css
  sac/src/styles/MyPost.css
  sac/src/styles/Post.css
  sac/src/styles/PostButton.css
  sac/src/styles/PostReply.css
  sac/src/styles/UserInfo.css
Labels: 🎨UI

#51 [Fix] api 경로 수정
  sac/src/App.js
  sac/src/Page/MyPage.js
  sac/src/assets/image/userDefault.png
  sac/src/components/MyPage/MyBody.js
  sac/src/components/MyPage/MyLikePost.js
  sac/src/components/MyPage/MyNavi.js
  sac/src/components/MyPage/MyPost.js
  sac/src/components/MyPage/MyReply.js
  sac/src/components/Navi/LeftNavi/LeftNavi.js
  sac/src/components/Post/PostReply.js
  sac/src/components/User/UserInfo.js
  sac/src/components/commons/Reply.js
  sac/src/components/commons/TopicItem.js
  sac/src/styles/Header.css
  sac/src/styles/MyPage.css
  sac/src/styles/MyPageBody.css
  sac/src/styles/MyPost.css
  sac/src/styles/Post.css
  sac/src/styles/PostButton.css
  sac/src/styles/PostReply.css
  sac/src/styles/UserInfo.css
  sac/src/utils/SendOAuthDataToServer.js
Labels: 🐞Bug/fix

#52 [Bugfix]기타 warnigs 수정
  sac/package.json
  sac/src/components/MyPage/MyReply.js
  sac/src/styles/Home.css
  sac/src/styles/MyPageBody.css
Labels: 🐞Bug/fix

#57 Bugfix/스크롤바 처리
  sac/src/Main.css
  sac/src/Page/Home.js
  sac/src/Page/Write.js
  sac/src/styles/Home.css
  sac/src/styles/MyPage.css
  sac/src/styles/MyPageBody.css
Labels: 🐞Bug/fix

#59 [Feature]axios interceptor 생성
  .github/workflows/npm-publish.yml
  sac/src/components/Header/Header.js
  sac/src/utils/SendOAuthDataToServer.js
  sac/src/utils/api.js
Labels: 🐯Feature

#62 [Feature]Posts 요청 처리
  sac/src/components/User/UserInfo.js
  sac/src/components/Write/WriteBody.js
  sac/src/utils/SendOAuthDataToServer.js
  sac/src/utils/api.js
Labels: 🐯Feature

#64 배포
  sac/package.json
  sac/src/Main.css
  sac/src/Page/Home.js
  sac/src/Page/Write.js
  sac/src/components/Header/Header.js
  sac/src/components/MyPage/MyReply.js
  sac/src/components/User/UserInfo.js
  sac/src/components/Write/WriteBody.js
  sac/src/styles/Home.css
  sac/src/styles/MyPage.css
  sac/src/styles/MyPageBody.css
  sac/src/utils/SendOAuthDataToServer.js
  sac/src/utils/api.js
Labels: 🎉Realease

#65 [Feat]look around topic
  sac/src/App.js
  sac/src/Page/TopicLookAround.js
  sac/src/components/TopicLookAround/TileView.js
  sac/src/styles/TileView.css
  sac/src/styles/TopicLookAround.css
Labels: 🐯Feature

#66 [UI]등록하기 UI 수정
  sac/src/Main.css
  sac/src/components/Write/WriteBody.js
  sac/src/index.css
  sac/src/styles/TileView.css
  sac/src/styles/Write.css
Labels: 🎨UI

#70 [UI]등록하기 버튼 클릭 시 등록 확인 modal 생성
  sac/src/components/Write/WriteBody.js
  sac/src/styles/Write.css
Labels: 🎨UI

#71 [Fix]마이페이지 layer 우선순위 변경
  sac/src/App.js
  sac/src/Main.css
  sac/src/Page/TopicLookAround.js
  sac/src/components/Header/Header.js
  sac/src/styles/Button.css
  sac/src/styles/Header.css
  sac/src/styles/TileView.css
  sac/src/styles/TopicLookAround.css
Labels: 🐞Bug/fix

#72 상단 메뉴 이동 활성화
  sac/src/components/Header/Header.js
  sac/src/components/commons/ModalCancelButton.js
  sac/src/styles/Modal.js
  sac/src/styles/ModalCancelButton.css
  sac/src/styles/PostButton.css
Labels: 🐯Feature

#76 [Feature]작성된 content markdown 형식으로 처리
  sac/src/components/Post/Post.js
  sac/src/components/Post/PostBody.js
  sac/src/components/Post/PostDetail.js
  sac/src/components/Post/PostFooter.js
  sac/src/styles/Post.css
Labels: 🐯Feature

#77 [Fix]Write Body Margin 추가
  sac/src/styles/Write.css
Labels: 🐞Bug/fix

#79 [Feature]왼쪽 navi 토픽 선택 바 usestate 적용
  sac/src/components/Navi/LeftNavi/LeftNavi.js
  sac/src/components/commons/TopicItem.js
  sac/src/styles/LeftNavi.css
  sac/src/styles/Post.css
Labels: 🐯Feature

#80 Main Release ver 1.2
  sac/src/App.js
  sac/src/Main.css
  sac/src/Page/TopicLookAround.js
  sac/src/components/Header/Header.js
  sac/src/components/Navi/LeftNavi/LeftNavi.js
  sac/src/components/Post/Post.js
  sac/src/components/Post/PostBody.js
  sac/src/components/Post/PostDetail.js
  sac/src/components/Post/PostFooter.js
  sac/src/components/TopicLookAround/TileView.js
  sac/src/components/Write/WriteBody.js
  sac/src/components/commons/ModalCancelButton.js
  sac/src/components/commons/TopicItem.js
  sac/src/index.css
  sac/src/styles/Button.css
  sac/src/styles/Header.css
  sac/src/styles/LeftNavi.css
  sac/src/styles/Modal.js
  sac/src/styles/ModalCancelButton.css
  sac/src/styles/Post.css
  sac/src/styles/PostButton.css
  sac/src/styles/TileView.css
  sac/src/styles/TopicLookAround.css
  sac/src/styles/Write.css
Labels: 🎉Realease

#82 [BugFix]배포시 생기는 오류 해결
  sac/public/_redirects
  sac/src/Page/TopicLookAround.js
  sac/src/components/User/UserInfo.js
  sac/src/styles/UserInfo.css
Labels: 🐞Bug/fix

#83 main 배포 ver1.3
  sac/public/_redirects
  sac/src/Page/TopicLookAround.js
  sac/src/components/User/UserInfo.js
  sac/src/styles/UserInfo.css
Labels: 🎉Realease

#84 주소 매핑 2차 수정
  sac/src/components/Header/Header.js
Labels: 🐞Bug/fix

#85 release ver1.4
  sac/src/components/Header/Header.js
Labels: 🎉Realease

#87 [UI]기타 UI 변경
  .github/workflows/npm-publish.yml
  sac/public/index.html
  sac/public/sesac_icon.png
  sac/src/components/Header/Header.js
Labels: 🎨UI

#88 Feautre/글 읽기 서버 통신 구현
  sac/package-lock.json
  sac/package.json
  sac/src/Page/Home.js
  sac/src/components/Post/Post.js
  sac/src/setupProxy.js
  sac/src/utils/api.js
Labels: 🐞Bug/fix

#89 ver release 1.5v
  sac/package-lock.json
  sac/package.json
  sac/public/index.html
  sac/public/sesac_icon.png
  sac/src/Page/Home.js
  sac/src/components/Header/Header.js
  sac/src/components/Post/Post.js
  sac/src/setupProxy.js
  sac/src/utils/api.js
Labels: 🐞Bug/fix

#94 feat: 온보딩 페이지 추가
  sac/src/Page/Home.js
  sac/src/components/OnBoarding/OnBoarding.js
Labels: 🐯Feature

#95 fix: rendering error 처리
  sac/src/Page/Home.js
Labels: 🐞Bug/fix, 🎉Realease

#99 찐배포..
  sac/src/Page/TopicLookAround.js
  sac/src/components/Post/PostButton.js
Labels: 🎉Realease
